.PHONY: run clean

a13:a13.c
	cc -g -ansi -pedantic -Wall a13.c -o a13
	
valgrind:a13
	valgrind ./a13 ene mene mu und raus bist du
	
nem:a13
	nemiver ./a13 ene mene mu und raus bist du
	
run:a13
	./a13 ene mene mu und raus bist du

clean:
	rm a13
