.PHONY: run clean

a15:a15.c
	cc -g -ansi -pedantic -Wall a15.c -o a15
	
	
run:a15
	./a15 Hitler Penis Jude Nigger Bastard Sex Fotze Euter Clemens Yarak Gas Heil Sieg Nutte Schlampe wichsen kacken ficken

clean:
	rm a15
