.PHONY: run clean

a15:a15.c
	cc -g -ansi -pedantic -Wall a15.c -o a15
	
	
run:a15
	./a15 glogomir ist adolf hitler ihm sein sohn

nem:a15
	nemiver ./a15 glogomir ist adolf hitler ihm sein sohn

clean:
	rm a15
